### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#2]
We need to add emails notifications.

I kinda want to build "callbacks" in general so we can make anything happen after a failed/success deploy. And you just add it to your list in your .criterion.yml file.

For example:

``` yaml
pass:
    - sh deploy.sh
    - email_notifications
fail:
    - email_notifications
```
